import type { Call, User, Comment, LeaderboardEntry, PriceLadderStep } from "./types";

export const users: User[] = [
  {
    id: "u_satoshi",
    handle: "satoshi",
    bio: "Routing the best takes on the internet.",
    twitter: "satoshi",
    verified: true,
    created_at: "2025-11-01T00:00:00Z",
    total_calls: 24,
    accuracy: 0.67,
    total_pnl: 42.5,
    watchers: 1840,
  },
  {
    id: "u_marginsmall",
    handle: "marginsmall",
    bio: "PQC, defense tech, asymmetric bets.",
    twitter: "marginsmall",
    verified: true,
    created_at: "2025-12-15T00:00:00Z",
    total_calls: 12,
    accuracy: 0.75,
    total_pnl: 89.3,
    watchers: 3200,
  },
  {
    id: "u_alice",
    handle: "alice",
    bio: "Macro + prediction markets. High conviction only.",
    twitter: "alice_trades",
    verified: true,
    created_at: "2026-01-05T00:00:00Z",
    total_calls: 8,
    accuracy: 0.6,
    total_pnl: 15.2,
    watchers: 720,
  },
  {
    id: "u_degen",
    handle: "degentrader",
    bio: null,
    twitter: null,
    verified: false,
    created_at: "2026-02-01T00:00:00Z",
    total_calls: 3,
    accuracy: null,
    total_pnl: null,
    watchers: 45,
  },
  {
    id: "u_macro_mike",
    handle: "macro_mike",
    bio: "Rates, FX, global macro. Ex-JPM.",
    twitter: "macro_mike_trades",
    verified: true,
    created_at: "2025-10-10T00:00:00Z",
    total_calls: 18,
    accuracy: 0.72,
    total_pnl: 64.1,
    watchers: 2100,
  },
  {
    id: "u_optionsqueen",
    handle: "optionsqueen",
    bio: "Vol surface is my love language.",
    twitter: "optionsqueen",
    verified: true,
    created_at: "2025-11-20T00:00:00Z",
    total_calls: 15,
    accuracy: 0.53,
    total_pnl: 31.8,
    watchers: 1560,
  },
  {
    id: "u_chad_perps",
    handle: "chad_perps",
    bio: "100x or nothing. Hyperliquid native.",
    twitter: null,
    verified: false,
    created_at: "2026-01-15T00:00:00Z",
    total_calls: 22,
    accuracy: 0.41,
    total_pnl: -12.5,
    watchers: 890,
  },
  {
    id: "u_thesis_machine",
    handle: "thesis_machine",
    bio: "Deep research, concentrated positions.",
    twitter: "thesis_machine",
    verified: true,
    created_at: "2025-09-01T00:00:00Z",
    total_calls: 9,
    accuracy: 0.78,
    total_pnl: 105.2,
    watchers: 4200,
  },
  {
    id: "u_kalshi_kid",
    handle: "kalshi_kid",
    bio: "Prediction markets are the future of price discovery.",
    twitter: "kalshi_kid",
    verified: true,
    created_at: "2025-12-01T00:00:00Z",
    total_calls: 31,
    accuracy: 0.65,
    total_pnl: 28.9,
    watchers: 1100,
  },
  {
    id: "u_threadguy",
    handle: "threadguy",
    bio: "Streams. Threads. Trades.",
    twitter: "threadguy",
    verified: false,
    created_at: "2026-02-16T00:00:00Z",
    total_calls: 1,
    accuracy: null,
    total_pnl: null,
    watchers: 890,
  },
  {
    id: "u_contrarian",
    handle: "contrarian",
    bio: "If everyone agrees, I'm probably short.",
    twitter: "contrarian_cap",
    verified: true,
    created_at: "2025-08-15T00:00:00Z",
    total_calls: 14,
    accuracy: 0.57,
    total_pnl: 19.4,
    watchers: 760,
  },
];

export const calls: Call[] = [
  {
    id: "c_msft_long",
    thesis: "MSFT owns the literal pipeline through which all AI-generated code flows — and it's at its cheapest multiple in 3 years",
    ticker: "MSFT",
    direction: "long",
    entry_price: 401,
    breakeven: "32% to be +EV",
    kills: "Copilot share drops below 30%; Azure revenue declines",
    caller_id: "u_satoshi",
    source_handle: "threadguy",
    source_url: "https://www.youtube.com/watch?v=threadguy-feb16",
    call_type: "curated",
    status: "active",
    resolve_price: null,
    resolve_date: null,
    resolve_pnl: null,
    resolve_note: null,
    created_at: "2026-02-16T20:00:00Z",
    instrument: "stock",
    platform: "robinhood",
    votes: 31,
    watchers: 890,
    comments: 9,
    source_quote: "100% of code is AI. Five SWEs independently confirmed they write zero human code post-Feb 5. Every one of those engineers runs their code through MSFT's tollbooth: VS Code, GitHub, Copilot, Azure, OpenAI.",
    reasoning: "GitHub Copilot has 20M+ users, 42% market share, and 90% of the Fortune 100. Copilot alone now generates more revenue than GitHub did when MSFT acquired it for $7.5B. MSFT trades at 25.2x earnings \u2014 20% below its 3-year average of 33.8x. At its historical average P/E, MSFT is a $530 stock \u2014 32% upside before a single dollar of incremental AI revenue.",
    edge: "Market is punishing MSFT for capex spending while ignoring that the AI coding market grew from $4.9B to $7.4B in a single year, projected to hit $30B by 2032. MSFT owns 42% of it.",
    counter: "Cursor (18% share) and Claude Code are eating into Copilot's lead. But even if Copilot's share drops to 30%, the total market is growing 27% annually \u2014 MSFT's absolute revenue still grows. Plus many competitors run on Azure. MSFT collects rent either way.",
    price_ladder: [
      { price: 361, pnl_pct: -10, pnl_dollars: -100, label: "stop / broad selloff" },
      { price: 401, pnl_pct: 0, pnl_dollars: 0, label: "breakeven" },
      { price: 461, pnl_pct: 15, pnl_dollars: 149, label: "50-day MA recovery" },
      { price: 530, pnl_pct: 32, pnl_dollars: 322, label: "P/E re-rates to 3yr avg" },
      { price: 555, pnl_pct: 38, pnl_dollars: 384, label: "52-week high" },
    ],
    alternative: "ACN $224 short (AI kills billable hours \u2014 buy puts at open)",
    scan_source: "THREADGUY Stream (Feb 16, 2026)",
  },
  {
    id: "c_dell_long",
    thesis: "Enterprise data security fears + cloud cost explosion will drive massive on-prem AI infrastructure spend",
    ticker: "DELL",
    direction: "long",
    entry_price: 117.49,
    breakeven: "50% to be +EV",
    kills: "Cloud AI costs drop 80%; enterprises abandon data sovereignty",
    caller_id: "u_satoshi",
    source_handle: "chamath",
    source_url: "https://www.youtube.com/watch?v=allin-feb2026",
    call_type: "curated",
    status: "active",
    resolve_price: null,
    resolve_date: null,
    resolve_pnl: null,
    resolve_note: null,
    created_at: "2026-02-16T14:00:00Z",
    instrument: "stock",
    platform: "robinhood",
    votes: 67,
    watchers: 3400,
    comments: 24,
    source_quote: "On-prem is back. It's going to happen. Do I, if I'm Geico, want to have all of my actuaries using all of our proprietary, private and confidential data on risk pricing in an open instance of an LLM? The answer is no. That's obvious.",
    reasoning: "Dell shipped $10B in AI servers in H1 FY2026 alone. Revenue guidance raised to $111.7B (+17% YoY). The stock is at $117 \u2014 30% below its 52-week high of $168 \u2014 while its AI backlog ($18.4B) is at all-time records growing 150% YoY. The market is punishing DELL on margin compression fears while ignoring that the on-prem enterprise shift is just beginning.",
    edge: "Stock sold off 30% while fundamentals accelerated. Market is pricing margin pressure from commodity servers, not the enterprise on-prem security premium \u2014 where enterprises will pay more to keep data in-house.",
    counter: "Friedberg pushed back on cloud private instances: \"Too expensive.\" Chamath agreed. This actually reinforces DELL \u2014 if cloud-hosted private AI is too expensive, physical on-prem from Dell/HPE are the alternative.",
    price_ladder: [
      { price: 89.55, pnl_pct: -24, pnl_dollars: -2375, label: "thesis wrong, AI server demand slows" },
      { price: 117.49, pnl_pct: 0, pnl_dollars: 0, label: "breakeven" },
      { price: 140.00, pnl_pct: 19, pnl_dollars: 1913, label: "re-rates to 200-day MA" },
      { price: 168.00, pnl_pct: 43, pnl_dollars: 4293, label: "returns to 52-week high" },
      { price: 180.00, pnl_pct: 53, pnl_dollars: 5313, label: "backlog converts, market re-prices on-prem" },
    ],
    alternative: "GLD $462 long (pure debasement hedge \u2014 less thesis-specific, more consensus)",
    scan_source: "All-In Podcast (Feb 2026)",
  },
  {
    id: "c_goog_short",
    thesis: "Google's ad monopoly is the casualty of AI search",
    ticker: "GOOG",
    direction: "short",
    entry_price: 172,
    breakeven: "22% to be +EV",
    kills: "AI search products flop; Google pivots to AI-first ads",
    caller_id: "u_satoshi",
    source_handle: "marginsmall",
    source_url: "https://x.com/marginsmall/status/1234567890",
    call_type: "curated",
    status: "active",
    resolve_price: null,
    resolve_date: null,
    resolve_pnl: null,
    resolve_note: null,
    created_at: "2026-02-14T10:30:00Z",
    instrument: "options",
    platform: "robinhood",
    votes: 42,
    watchers: 2100,
    comments: 18,
  },
  {
    id: "c_laes_long",
    thesis: "PQC mandate will create a new semiconductor category",
    ticker: "LAES",
    direction: "long",
    entry_price: 3.85,
    breakeven: "40% to be +EV",
    kills: "NIST delays mandate past 2028; LAES fails to win any gov contracts",
    caller_id: "u_satoshi",
    source_handle: "marginsmall",
    source_url: "https://x.com/marginsmall/status/9876543210",
    call_type: "curated",
    status: "active",
    resolve_price: null,
    resolve_date: null,
    resolve_pnl: null,
    resolve_note: null,
    created_at: "2026-02-12T08:15:00Z",
    instrument: "stock",
    platform: "robinhood",
    votes: 5,
    watchers: 1200,
    comments: 8,
  },
  {
    id: "c_resolved_win",
    thesis: "Ozempic supply chain bottleneck resolves by Q1 -- NVO rips",
    ticker: "NVO",
    direction: "long",
    entry_price: 89.5,
    breakeven: "15% to be +EV",
    kills: "FDA delays approval of expanded manufacturing; insurance coverage pullback",
    caller_id: "u_marginsmall",
    source_handle: null,
    source_url: null,
    call_type: "original",
    status: "resolved",
    resolve_price: 282.7,
    resolve_date: "2026-02-10T16:00:00Z",
    resolve_pnl: 218,
    resolve_note: "Supply chain normalized faster than expected. NVO hit all-time high.",
    created_at: "2025-09-20T14:00:00Z",
    instrument: "stock",
    platform: "robinhood",
    votes: 156,
    watchers: 4800,
    comments: 67,
  },
  {
    id: "c_kalshi_fed",
    thesis: "Fed holds rates through March FOMC -- no cut despite market pressure",
    ticker: "KXFEDRATE",
    direction: "short",
    entry_price: 0.62,
    breakeven: "Binary: 62c risk for 38c profit",
    kills: "Surprise CPI collapse; emergency financial event forces cut",
    caller_id: "u_alice",
    source_handle: null,
    source_url: null,
    call_type: "original",
    status: "active",
    resolve_price: null,
    resolve_date: null,
    resolve_pnl: null,
    resolve_note: null,
    created_at: "2026-02-15T09:00:00Z",
    instrument: "kalshi",
    platform: "kalshi",
    votes: 28,
    watchers: 890,
    comments: 12,
  },
  {
    id: "c_expired",
    thesis: "Tesla robotaxi fleet launches in Austin by EOY 2025",
    ticker: "TSLA",
    direction: "long",
    entry_price: 248,
    breakeven: "30% to be +EV",
    kills: "Regulatory delays; hardware not ready; Waymo dominance in Austin",
    caller_id: "u_degen",
    source_handle: null,
    source_url: null,
    call_type: "original",
    status: "expired",
    resolve_price: 310,
    resolve_date: "2026-01-31T00:00:00Z",
    resolve_pnl: null,
    resolve_note: "No robotaxi fleet launched. Card expired after 6 months.",
    created_at: "2025-07-15T12:00:00Z",
    instrument: "stock",
    platform: "robinhood",
    votes: 8,
    watchers: 320,
    comments: 4,
  },
  {
    id: "c_hype_perps",
    thesis: "ETH breaks $5K on ETF inflows before BTC halving narrative fades",
    ticker: "ETH-USD",
    direction: "long",
    entry_price: 3200,
    breakeven: "18% to be +EV",
    kills: "SEC delays spot ETH ETF; macro risk-off event; BTC dominance surge",
    caller_id: "u_alice",
    source_handle: null,
    source_url: null,
    call_type: "original",
    status: "active",
    resolve_price: null,
    resolve_date: null,
    resolve_pnl: null,
    resolve_note: null,
    created_at: "2026-02-10T11:00:00Z",
    instrument: "perps",
    platform: "hyperliquid",
    votes: 15,
    watchers: 560,
    comments: 6,
  },
];

export const comments: Comment[] = [
  {
    id: "cm_1",
    call_id: "c_goog_short",
    user_id: "u_alice",
    content: "Bold thesis. The breakeven feels tight though -- 22% assumes puts stay cheap.",
    parent_id: null,
    created_at: "2026-02-14T12:00:00Z",
  },
  {
    id: "cm_2",
    call_id: "c_goog_short",
    user_id: "u_satoshi",
    content: "IV is historically low for GOOG right now. That's the edge.",
    parent_id: "cm_1",
    created_at: "2026-02-14T12:30:00Z",
  },
  {
    id: "cm_3",
    call_id: "c_resolved_win",
    user_id: "u_alice",
    content: "Incredible call. The supply chain thesis was contrarian at the time.",
    parent_id: null,
    created_at: "2026-02-10T17:00:00Z",
  },
  {
    id: "cm_4",
    call_id: "c_laes_long",
    user_id: "u_degen",
    content: "LAES has no revenue. This is pure speculation.",
    parent_id: null,
    created_at: "2026-02-13T09:00:00Z",
  },
  {
    id: "cm_5",
    call_id: "c_laes_long",
    user_id: "u_marginsmall",
    content: "Revenue comes after the mandate. That's the whole thesis.",
    parent_id: "cm_4",
    created_at: "2026-02-13T10:00:00Z",
  },
];

export const leaderboard: LeaderboardEntry[] = [
  { rank: 1, user: users[7]!, original_calls: 9, curated_calls: 0 },   // thesis_machine
  { rank: 2, user: users[1]!, original_calls: 8, curated_calls: 4 },   // marginsmall
  { rank: 3, user: users[4]!, original_calls: 10, curated_calls: 8 },  // macro_mike
  { rank: 4, user: users[0]!, original_calls: 6, curated_calls: 18 },  // satoshi
  { rank: 5, user: users[8]!, original_calls: 31, curated_calls: 0 },  // kalshi_kid
  { rank: 6, user: users[2]!, original_calls: 8, curated_calls: 0 },   // alice
  { rank: 7, user: users[9]!, original_calls: 12, curated_calls: 2 },  // contrarian
  { rank: 8, user: users[5]!, original_calls: 12, curated_calls: 3 },  // optionsqueen
  { rank: 9, user: users[6]!, original_calls: 22, curated_calls: 0 },  // chad_perps
  { rank: 10, user: users[3]!, original_calls: 3, curated_calls: 0 },  // degentrader
];

// Helper to look up user by id
export function getUserById(id: string): User | undefined {
  return users.find((u) => u.id === id);
}

// Helper to look up user by handle
export function getUserByHandle(handle: string): User | undefined {
  return users.find((u) => u.handle === handle);
}

// Helper to get calls for a user
export function getCallsByUser(userId: string): Call[] {
  return calls.filter((c) => c.caller_id === userId);
}

// Helper to get comments for a call
export function getCommentsForCall(callId: string): Comment[] {
  return comments.filter((c) => c.call_id === callId);
}

// Helper to get call by id
export function getCallById(id: string): Call | undefined {
  return calls.find((c) => c.id === id);
}
