import type { Call, User, Comment, LeaderboardEntry, PriceLadderStep, DerivationChain } from "./types";

export const users: User[] = [
  {
    id: "u_satoshi",
    handle: "satoshi",
    bio: "Routing the best takes on the internet.",
    twitter: "satoshi",
    verified: true,
    created_at: "2025-11-01T00:00:00Z",
    total_calls: 5,
    accuracy: null,
    total_pnl: null,
    watchers: 1840,
  },
  {
    id: "u_chamath",
    handle: "chamath",
    bio: "CEO of Social Capital. All-In Podcast.",
    twitter: "chamath",
    avatar_url: "https://pbs.twimg.com/profile_images/1883600182165848064/-9LbG3md_400x400.jpg",
    verified: false,
    created_at: "2026-02-16T00:00:00Z",
    total_calls: 1,
    accuracy: null,
    total_pnl: null,
    watchers: 12400,
  },
  {
    id: "u_threadguy",
    handle: "threadguy",
    bio: "Streams. Threads. Trades.",
    twitter: "notthreadguy",
    avatar_url: "https://pbs.twimg.com/profile_images/1920651894982066176/ssOaEU8k_400x400.jpg",
    verified: false,
    created_at: "2026-02-16T00:00:00Z",
    total_calls: 1,
    accuracy: null,
    total_pnl: null,
    watchers: 890,
  },
  {
    id: "u_shkreli",
    handle: "martinshkreli",
    bio: "Pharma, biotech, deep value. You know who I am.",
    twitter: "MartinShkreli",
    avatar_url: "https://pbs.twimg.com/profile_images/1904997844748005376/wFfbBUBD_400x400.jpg",
    verified: false,
    created_at: "2026-02-17T00:00:00Z",
    total_calls: 2,
    accuracy: null,
    total_pnl: null,
    watchers: 5200,
  },
  {
    id: "u_marginsmall",
    handle: "marginsmall",
    bio: "PQC, defense tech, asymmetric bets.",
    twitter: "marginsmall",
    avatar_url: "https://pbs.twimg.com/profile_images/1528733512861351936/0S5zDezo_400x400.jpg",
    verified: false,
    created_at: "2025-12-15T00:00:00Z",
    total_calls: 1,
    accuracy: null,
    total_pnl: null,
    watchers: 3200,
  },
  {
    id: "u_nicbstme",
    handle: "nicbstme",
    bio: "Financial data infrastructure, moat analysis.",
    twitter: "nicbstme",
    verified: false,
    created_at: "2026-02-17T00:00:00Z",
    total_calls: 1,
    accuracy: null,
    total_pnl: null,
    watchers: 420,
  },
];

export const calls: Call[] = [
  {
    id: "c_dell_long",
    thesis: "Enterprise data security fears + cloud cost explosion will drive massive on-prem AI infrastructure spend",
    ticker: "DELL",
    direction: "long",
    entry_price: 117.49,
    breakeven: "50% to be +EV",
    kills: "Cloud AI costs drop 80%; enterprises abandon data sovereignty",
    caller_id: "u_satoshi",
    source_handle: "chamath",
    source_url: "https://www.youtube.com/watch?v=allin-feb2026",
    call_type: "derived",
    status: "active",
    resolve_price: null,
    resolve_date: null,
    resolve_pnl: null,
    resolve_note: null,
    created_at: "2026-02-16T14:00:00Z",
    instrument: "stock",
    platform: "robinhood",
    votes: 67,
    watchers: 3400,
    comments: 24,
    derivation: {
      source_said: "On-prem is back.",
      implies: "enterprise data sovereignty fears → on-prem AI infrastructure spend",
      searching_for: "On-prem AI server companies with accelerating backlog, sold off on margin fears",
      found_because: "Dell shipped $10B AI servers H1, backlog $18.4B (150% YoY), stock -30% from highs",
      chose_over: "HPE (lower AI backlog growth), SMCI (accounting risk) — Dell has the enterprise relationship + backlog proof",
    },
    source_quote: "On-prem is back. It's going to happen. Do I, if I'm Geico, want to have all of my actuaries using all of our proprietary, private and confidential data on risk pricing in an open instance of an LLM? The answer is no. That's obvious.",
    reasoning: "Dell shipped $10B in AI servers in H1 FY2026 alone. Revenue guidance raised to $111.7B (+17% YoY). The stock is at $117 \u2014 30% below its 52-week high of $168 \u2014 while its AI backlog ($18.4B) is at all-time records growing 150% YoY. The market is punishing DELL on margin compression fears while ignoring that the on-prem enterprise shift is just beginning.",
    edge: "Stock sold off 30% while fundamentals accelerated. Market is pricing margin pressure from commodity servers, not the enterprise on-prem security premium \u2014 where enterprises will pay more to keep data in-house.",
    counter: "Friedberg pushed back on cloud private instances: \"Too expensive.\" Chamath agreed. This actually reinforces DELL \u2014 if cloud-hosted private AI is too expensive, physical on-prem from Dell/HPE are the alternative.",
    price_ladder: [
      { price: 89.55, pnl_pct: -24, pnl_dollars: -2375, label: "thesis wrong, AI server demand slows" },
      { price: 117.49, pnl_pct: 0, pnl_dollars: 0, label: "breakeven" },
      { price: 140.00, pnl_pct: 19, pnl_dollars: 1913, label: "re-rates to 200-day MA" },
      { price: 168.00, pnl_pct: 43, pnl_dollars: 4293, label: "returns to 52-week high" },
      { price: 180.00, pnl_pct: 53, pnl_dollars: 5313, label: "backlog converts, market re-prices on-prem" },
    ],
    alternative: "GLD $462 long (pure debasement hedge \u2014 less thesis-specific, more consensus)",
    scan_source: "All-In Podcast (Feb 2026)",
  },
  {
    id: "c_msft_long",
    thesis: "MSFT owns the literal pipeline through which all AI-generated code flows — and it's at its cheapest multiple in 3 years",
    ticker: "MSFT",
    direction: "long",
    entry_price: 401,
    breakeven: "32% to be +EV",
    kills: "Copilot share drops below 30%; Azure revenue declines",
    caller_id: "u_satoshi",
    source_handle: "threadguy",
    source_url: "https://www.youtube.com/watch?v=threadguy-feb16",
    call_type: "derived",
    status: "active",
    resolve_price: null,
    resolve_date: null,
    resolve_pnl: null,
    resolve_note: null,
    created_at: "2026-02-16T20:00:00Z",
    instrument: "stock",
    platform: "robinhood",
    votes: 31,
    watchers: 890,
    comments: 9,
    derivation: {
      source_said: "100% of code is AI.",
      implies: "ai coding is universal dependency → tollbooth owner collects rent",
      searching_for: "Companies owning the AI coding tollbooth (IDE, hosting, model API), trading below historical multiples",
      found_because: "MSFT owns VS Code + GitHub + Copilot (42% share) + Azure + OpenAI stake, at 25.2x earnings vs 33.8x 3yr avg",
      chose_over: "GOOG (competing but no IDE lock-in), ADBE (creative not code) — MSFT owns the full stack: IDE + host + model",
    },
    source_quote: "100% of code is AI. Five SWEs independently confirmed they write zero human code post-Feb 5. Every one of those engineers runs their code through MSFT's tollbooth: VS Code, GitHub, Copilot, Azure, OpenAI.",
    reasoning: "GitHub Copilot has 20M+ users, 42% market share, and 90% of the Fortune 100. Copilot alone now generates more revenue than GitHub did when MSFT acquired it for $7.5B. MSFT trades at 25.2x earnings \u2014 20% below its 3-year average of 33.8x. At its historical average P/E, MSFT is a $530 stock \u2014 32% upside before a single dollar of incremental AI revenue.",
    edge: "Market is punishing MSFT for capex spending while ignoring that the AI coding market grew from $4.9B to $7.4B in a single year, projected to hit $30B by 2032. MSFT owns 42% of it.",
    counter: "Cursor (18% share) and Claude Code are eating into Copilot's lead. But even if Copilot's share drops to 30%, the total market is growing 27% annually \u2014 MSFT's absolute revenue still grows. Plus many competitors run on Azure. MSFT collects rent either way.",
    price_ladder: [
      { price: 361, pnl_pct: -10, pnl_dollars: -100, label: "stop / broad selloff" },
      { price: 401, pnl_pct: 0, pnl_dollars: 0, label: "breakeven" },
      { price: 461, pnl_pct: 15, pnl_dollars: 149, label: "50-day MA recovery" },
      { price: 530, pnl_pct: 32, pnl_dollars: 322, label: "P/E re-rates to 3yr avg" },
      { price: 555, pnl_pct: 38, pnl_dollars: 384, label: "52-week high" },
    ],
    alternative: "ACN $224 short (AI kills billable hours \u2014 buy puts at open)",
    scan_source: "THREADGUY Stream (Feb 16, 2026)",
  },
  {
    id: "c_ionq_long",
    thesis: "Quantum selloff was mechanical (quant unwind), not fundamental — IonQ is cheaper than its private peers at $12.3B",
    ticker: "IONQ",
    direction: "long",
    entry_price: 34.11,
    breakeven: "40% to be +EV",
    kills: "Rate cuts delayed past Q3; DARPA Stage C rejection",
    caller_id: "u_satoshi",
    source_handle: "martinshkreli",
    source_url: null,
    call_type: "derived",
    status: "active",
    resolve_price: null,
    resolve_date: null,
    resolve_pnl: null,
    resolve_note: null,
    created_at: "2026-02-17T10:00:00Z",
    instrument: "stock",
    platform: "robinhood",
    votes: 18,
    watchers: 1400,
    comments: 7,
    derivation: {
      source_said: "Quantum selloff was mechanical, not fundamental.",
      implies: "quant unwind sold public quantum below private valuations → reversion trade",
      searching_for: "Public quantum companies trading below comparable private round valuations, with upcoming catalysts",
      found_because: "IonQ at $12.3B after -60% drawdown, stronger gov contracts than Quantinuum ($10B private) or PsiQuantum ($7B private)",
      chose_over: "RGTI (higher beta but no DARPA Stage B), QBTS (thinner contract book) — IonQ has strongest gov pipeline",
    },
    source_quote: "Bloomberg confirmed quants suffered their worst drawdown since October in the first two weeks of January, down 2.8% per UBS prime book estimates. Goldman prime data showed systematic long-short managers in their worst 10-day stretch simultaneously. This wasn't a story about quantum fundamentals deteriorating — it was forced selling by systematic strategies rotating out of last year's hottest momentum factor.",
    reasoning: "The public-private disconnect is real and measurable. Quantinuum closed at $10B, PsiQuantum raised at $7B from BlackRock and Nvidia's venture arm — both rising. Meanwhile IonQ trades at $12.3B after a 60% drawdown, with a stronger government contract book than either private peer ($100M+ USAF contracts, DARPA QBI Stage B selection). Rigetti at $5.3B is cheaper than PsiQuantum's private round despite having live hardware and revenue.",
    edge: "Catalyst calendar is dense: DARPA Stage C selections in 2026, EU Quantum Grand Challenge funding, Xanadu's $3.1B SPAC closing Q1 2026 repricing every public comp. The US government is discussing taking equity stakes in quantum companies — a structure that puts a floor under valuations.",
    counter: "These are still 300x revenue companies. The quant rebalancing narrative is convenient but valuations were objectively stretched before the selloff. Quantum's commercial timeline (DARPA says utility-scale by 2033) is 7+ years out. Private market raises have survivorship bias.",
    price_ladder: [
      { price: 30.70, pnl_pct: -10, pnl_dollars: -100, label: "stop loss, 10% below entry" },
      { price: 45.97, pnl_pct: 35, pnl_dollars: 344, label: "reclaim 50-day MA" },
      { price: 69.48, pnl_pct: 104, pnl_dollars: 1026, label: "midpoint 52W range (2x)" },
      { price: 84.64, pnl_pct: 148, pnl_dollars: 1466, label: "retest 52W high (2.5x)" },
    ],
    alternative: "RGTI $16.09 long (higher beta, -72% drawdown, no DARPA Stage B)",
    scan_source: "Martin Shkreli (Feb 2026)",
  },
  {
    id: "c_evr_long",
    thesis: "IPO wave is consensus for MS/GS but the non-obvious play is Evercore — pure advisory, more leverage to the fee surge",
    ticker: "EVR",
    direction: "long",
    entry_price: 322,
    breakeven: "55% to be +EV",
    kills: "IPO freeze; credit event shuts the window",
    caller_id: "u_satoshi",
    source_handle: "martinshkreli",
    source_url: null,
    call_type: "derived",
    status: "active",
    resolve_price: null,
    resolve_date: null,
    resolve_pnl: null,
    resolve_note: null,
    created_at: "2026-02-17T10:30:00Z",
    instrument: "stock",
    platform: "robinhood",
    votes: 12,
    watchers: 780,
    comments: 3,
    derivation: {
      source_said: "Michael Grimes is back at Morgan Stanley. The IPO factory restarts.",
      implies: "ipo wave is consensus for MS/GS → non-obvious play is pure-play advisory",
      searching_for: "Boutique advisory firms with pure fee exposure to IPO/M&A volume, better entry than diversified banks",
      found_because: "EVR: pure advisory, 50%+ margins, -17% from 52W high vs MS/GS already at consensus targets",
      chose_over: "MS (already at consensus target, diversified), GS (same) — EVR is pure advisory, 50%+ margins, better entry",
    },
    source_quote: "Michael Grimes walking back into Morgan Stanley in February 2026 is the signal the IPO factory restarts at full capacity. Goldman CEO Solomon is calling 2026 a 'record-breaking year for M&A,' SEC Chair Atkins is coordinating what they're both calling the 'Great IPO Wave.' Pipeline is real: SpaceX ($1.5T), Databricks ($134B), Stripe ($120B), potentially OpenAI and Anthropic.",
    reasoning: "MS at $171 and GS at $905 have already priced in a strong 2026. MS consensus target is $180-195 — that's 5-14% upside. IPO underwriting is one revenue stream among many. The non-obvious play is Evercore: pure-play advisory, no trading desk, no consumer banking diluting the story. Fee-based revenue at 50%+ margins. At $322, it's 17% below its 52W high of $389 and below its 50-day MA — a better entry than MS.",
    edge: "When IPO volume surges, boutique advisors get pulled into every deal as co-advisors and fairness opinion providers. EVR has more leverage to the thesis than the diversified banks, with a better technical entry.",
    counter: "IPO windows slam shut overnight — tariffs, credit events, or AI winter freeze the pipeline. EVR advises but doesn't underwrite (less direct than MS/GS). Stock already ran 116% in 12 months.",
    price_ladder: [
      { price: 290, pnl_pct: -10, pnl_dollars: -97, label: "stop loss, IPO window closes" },
      { price: 352, pnl_pct: 9, pnl_dollars: 89, label: "50-day MA reclaim" },
      { price: 370, pnl_pct: 15, pnl_dollars: 143, label: "multiple IPO mandates announced" },
      { price: 389, pnl_pct: 21, pnl_dollars: 201, label: "52W high retest, record IPO year" },
    ],
    alternative: "IPO ETF $43.46 long (higher beta on IPO performance, -20% from highs)",
    scan_source: "Martin Shkreli (Feb 2026)",
  },
  {
    id: "c_spgi_long",
    thesis: "S&P Global is a regulatory fortress disguised as a financial data terminal — the market is selling it like it's another search layer over public data",
    ticker: "SPGI",
    direction: "long",
    entry_price: 409.54,
    breakeven: "35% to be +EV",
    kills: "Credit issuance collapses; NRSRO deregulated; AI displaces ratings oligopoly",
    caller_id: "u_satoshi",
    source_handle: "nicbstme",
    source_url: "https://x.com/nicbstme/status/2023501562480644501",
    call_type: "inspired",
    status: "active",
    resolve_price: null,
    resolve_date: null,
    resolve_pnl: null,
    resolve_note: null,
    created_at: "2026-02-17T16:00:00Z",
    instrument: "stock",
    platform: "robinhood",
    votes: 8,
    watchers: 620,
    comments: 4,
    reasoning: "The market dropped SPGI 29% alongside FactSet's 57% decline, painting every financial data company with the same 'AI disrupts terminals' brush. But SPGI passes all three survival tests: proprietary data (credit ratings), regulatory lock-in (NRSRO designation), and transaction embedding (S&P indices power $7T+ in passive investing). A $0.35 EPS miss triggered a 25% selloff on a company guiding 6-8% organic revenue growth. Forward P/E compressed from ~30x to ~21x — a level SPGI hasn't traded at since the 2020 panic.",
    edge: "Insiders buying the dip. Wall Street consensus remains 'Strong Buy' with $528 average target. The selloff was driven by a small EPS miss, not structural failure. An LLM can't issue an NRSRO-certified rating any more than it can perform surgery.",
    counter: "FactSet short is the obvious play (already down 57%, 13x P/E — multiple already compressed from 40x). MCO has purer ratings exposure but trades at 33x with binary earnings risk. SPGI's Market Intelligence segment (~45% of revenue) IS exposed to AI search disruption, but multi-year contracts provide 12-24 months of floor.",
    price_ladder: [
      { price: 382, pnl_pct: -7, pnl_dollars: -55, label: "52W low / recession" },
      { price: 410, pnl_pct: 0, pnl_dollars: 0, label: "breakeven — dead money" },
      { price: 493, pnl_pct: 20, pnl_dollars: 167, label: "50-day MA reversion" },
      { price: 528, pnl_pct: 29, pnl_dollars: 237, label: "analyst consensus" },
      { price: 558, pnl_pct: 36, pnl_dollars: 297, label: "pre-selloff levels" },
    ],
    alternative: "MCO $426 long (purer ratings, but 33x P/E + earnings tomorrow)",
    scan_source: "nicbstme AI vs Financial Data (Feb 2026)",
    derivation: {
      source_said: "When the interface layer gets commoditized, the scarce inputs get more valuable",
      implies: "proprietary data creators benefit from ai disrupting terminals",
      searching_for: "Financial data companies with regulatory lock-in or benchmark ownership, recently sold off",
      found_because: "NRSRO-certified credit ratings + $7T indexed to S&P indices — scarce inputs AI can't replicate — but sold off 29% alongside FactSet",
      chose_over: "MCO (purer ratings but 33x P/E + earnings risk), FactSet short (already -57%, obvious) — SPGI has ratings + indices, dual moat",
    },
  },
  {
    id: "c_laes_long",
    thesis: "NIST PQC mandate creates a new hardware upgrade cycle — LAES is the only public pure-play making the silicon for it",
    ticker: "LAES",
    direction: "long",
    entry_price: 3.88,
    breakeven: "40% to be +EV",
    kills: "NIST delays mandate past 2028; QS7001 commercialization slips",
    caller_id: "u_satoshi",
    source_handle: "marginsmall",
    source_url: null,
    call_type: "derived",
    status: "active",
    resolve_price: null,
    resolve_date: null,
    resolve_pnl: null,
    resolve_note: null,
    created_at: "2026-02-17T10:00:00Z",
    instrument: "stock",
    platform: "robinhood",
    votes: 5,
    watchers: 1200,
    comments: 8,
    source_quote: "ai overbuild, 2027 compute glut, 2028/2030 washout, quantum plugs into ai subsidised infra to meet 2030/2035 nist deadline. saas meltdown but pqc software still has nist tailwinds via us gov",
    reasoning: "SEALSQ makes the QS7001, the first hardware-embedded post-quantum chip. Revenue hit $18M for FY 2025, up 66% YoY, with Q4 alone doing $8M. Pipeline is $200M through 2028, with $60M+ tied to PQC-specific products. Federal systems must start transitioning to CNSA 2.0 by January 2027. RSA and ECDSA get deprecated by 2030, fully disallowed by 2035. This isn't optional — it's a compliance mandate that creates a new hardware upgrade cycle.",
    edge: "LSCC launched CNSA 2.0-compliant FPGAs and trades at $97.50 with a $13.3B market cap, but PQC is a feature for Lattice, not the business. The stock already ran from $35 to $98. LAES at $694M market cap with PQC as 100% of the story has more thesis beta. If the PQC mandate drives the spending, LAES moves multiples, not percentages.",
    counter: "LAES is a $694M micro-cap doing $18M revenue — speculative growth. If QS7001 commercialization slips past H2 2026 or the $200M pipeline doesn't convert, the stock can revisit $2. The 52-week low is $1.99. Counter: revenue is accelerating (Q4 alone was $8M — annualized run rate $32M) and the government mandate is non-discretionary.",
    price_ladder: [
      { price: 1.99, pnl_pct: -49, pnl_dollars: -48700, label: "thesis wrong, revisit 52W low" },
      { price: 3.88, pnl_pct: 0, pnl_dollars: 0, label: "breakeven" },
      { price: 5.40, pnl_pct: 39, pnl_dollars: 39200, label: "pipeline converts, QS7001 ships" },
      { price: 6.17, pnl_pct: 59, pnl_dollars: 59000, label: "IV-implied 90-day target" },
      { price: 8.71, pnl_pct: 124, pnl_dollars: 124500, label: "52W high retest" },
    ],
    alternative: "LSCC $97.50 long (PQC via FPGA, safer but diluted + already ran 181%)",
    derivation: {
      source_said: "pqc software still has nist tailwinds via us gov",
      implies: "nist pqc deadline → mandatory quantum-resistant hardware upgrades",
      searching_for: "Pure-play PQC semiconductor companies with government contract pipeline",
      found_because: "LAES is the only public pure-play PQC chip company — QS7001 shipping, $18M rev (+66% YoY), $200M pipeline through 2028",
      chose_over: "LSCC (CNSA 2.0 FPGAs but PQC is <10% of revenue, already +181%), MCHP (crypto-agile MCUs, even more diluted) — LAES is 100% PQC, highest thesis beta",
    },
    scan_source: "marginsmall (Feb 2026)",
  },
];

export const comments: Comment[] = [];

export const leaderboard: LeaderboardEntry[] = [
  { rank: 1, user: users[0]!, original_calls: 0, curated_calls: 5 },  // satoshi
  { rank: 2, user: users[3]!, original_calls: 0, curated_calls: 2 },  // martinshkreli (source)
  { rank: 3, user: users[1]!, original_calls: 0, curated_calls: 1 },  // chamath (source)
  { rank: 4, user: users[2]!, original_calls: 0, curated_calls: 1 },  // threadguy (source)
  { rank: 5, user: users[5]!, original_calls: 0, curated_calls: 1 },  // nicbstme (source)
];

// Helper to look up user by id
export function getUserById(id: string): User | undefined {
  return users.find((u) => u.id === id);
}

// Helper to look up user by handle
export function getUserByHandle(handle: string): User | undefined {
  return users.find((u) => u.handle === handle);
}

// Helper to get calls for a user
export function getCallsByUser(userId: string): Call[] {
  return calls.filter((c) => c.caller_id === userId);
}

// Helper to get comments for a call
export function getCommentsForCall(callId: string): Comment[] {
  return comments.filter((c) => c.call_id === callId);
}

// Helper to get call by id
export function getCallById(id: string): Call | undefined {
  return calls.find((c) => c.id === id);
}
